#!/usr/bin/env bash
set -e

#Download latest neovim appimage
wget "https://github.com/neovim/neovim/releases/download/v0.10.2/nvim.appimage"

#Install nvim 
chmod u+x nvim.appimage
./nvim.appimage --appimage-extract
ln -s /squashfs-root/usr/bin/nvim /usr/local/bin/nvim 

#Install lazyvim
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git

